CREATE DATABASE TaiChinh
GO
USE TaiChinh
GO
CREATE TABLE KhachHang(
MaKH CHAR(10) NOT NULL,
HoTen VARCHAR(50) NOT NULL ,
DiaChi VARCHAR(50) NOT NULL,
DienThoai VARCHAR(10), --UNIQUE, -- la duy nhat
NgaySinh Date
)
GO
CREATE TABLE NhanVien(
MaNV CHAR(10) NOT NULL,
HoTen VARCHAR(50) NOT NULL,
DiaChi VARCHAR(50) NOT NULL,
DienThoai VARCHAR(10), --UNIQUE,
NgaySinh DATE,
ChucVu VARCHAR(30),
NgayVaoLam DATE
)
GO
CREATE TABLE TaiSan(
MaTaiSan CHAR(10) NOT NULL,
TenTaiSan VARCHAR(70),
LoaiTaiSan VARCHAR(30),
GiaTri MONEY,
)
GO
CREATE TABLE Vay(
MaVay CHAR(10) NOT NULL,
MaKH CHAR(10),
MaTaiSan CHAR(10),
NgayVay DATE NOT NULL,
ThoiHan INT,
LaiSuat FLOAT,
SoTienVay MONEY,
NgayHetHan DATE
)
GO
ALTER TABLE KhachHang
ADD CONSTRAINT pk_kh PRIMARY KEY(MaKH)

ALTER TABLE NhanVien
ADD CONSTRAINT manv PRIMARY KEY(MaNV)

ALTER TABLE TaiSan
ADD CONSTRAINT mats PRIMARY KEY(MaTaiSan)

ALTER TABLE Vay
ADD CONSTRAINT mav PRIMARY KEY(MaVay)

ALTER TABLE Vay
ADD CONSTRAINT mav2 FOREIGN KEY(MaKH)
REFERENCES KhachHang(MaKH)

ALTER TABLE Vay
ADD CONSTRAINT mav2 FOREIGN KEY(MaNV)
REFERENCES NhanVien(MaNV)

ALTER TABLE KhachHang
ADD CONSTRAINT DT UNIQUE(DienThoai)

ALTER TABLE NhanVien
ADD CONSTRAINT DT2 UNIQUE(DienThoai)

ALTER TABLE NhanVien
ADD CONSTRAINT nvl CHECK (NgayVaoLam > '1995/1/1')

ALTER TABLE Vay
ADD CONSTRAINT nvay CHECK (NgayVay = GETDATE())

ALTER TABLE Vay
ADD CONSTRAINT nhh CHECK (NgayHetHan > Ngayvay)

ALTER TABLE TaiSan
ADD CONSTRAINT gt CHECK (GiaTri >=0)

ALTER TABLE Vay
ADD CONSTRAINT th CHECK (ThoiHan >= 1 AND ThoiHan <=36)